<?php

define('FRAMEWORK_RGDND_ITEM_ROOT', FRAMEWORK_RGDND_ROOT . '/Libraries/Item');
define('FRAMEWORK_RGDND_ITEM_BASECLASSES', FRAMEWORK_RGDND_ITEM_ROOT . '/Baseclasses');
define('FRAMEWORK_RGDND_ITEM_CONFIG', FRAMEWORK_RGDND_ITEM_ROOT . '/Config');
define('FRAMEWORK_RGDND_ITEM_DATA', FRAMEWORK_RGDND_ITEM_ROOT . '/Data');
define('FRAMEWORK_RGDND_ITEM_FACTORIES', FRAMEWORK_RGDND_ITEM_ROOT . '/Factories');
define('FRAMEWORK_RGDND_ITEM_PERFORMERS', FRAMEWORK_RGDND_ITEM_ROOT . '/Performers');
define('FRAMEWORK_RGDND_ITEM_READERS', FRAMEWORK_RGDND_ITEM_ROOT . '/Readers');
define('FRAMEWORK_RGDND_ITEM_UTILS', FRAMEWORK_RGDND_ITEM_ROOT . '/Utils');

require_once(FRAMEWORK_RGDND_ROOT . '/Libraries/Shared/Config/config.php');