<?php

define('FRAMEWORK_RGDND_SHARED_ROOT', FRAMEWORK_RGDND_ROOT . '/Libraries/Shared');
define('FRAMEWORK_RGDND_SHARED_BASECLASSES', FRAMEWORK_RGDND_SHARED_ROOT . '/Baseclasses');
define('FRAMEWORK_RGDND_SHARED_CONFIG', FRAMEWORK_RGDND_SHARED_ROOT . '/Config');
define('FRAMEWORK_RGDND_SHARED_DATA', FRAMEWORK_RGDND_SHARED_ROOT . '/Data');
define('FRAMEWORK_RGDND_SHARED_FACTORIES', FRAMEWORK_RGDND_SHARED_ROOT . '/Factories');
define('FRAMEWORK_RGDND_SHARED_READERS', FRAMEWORK_RGDND_SHARED_ROOT . '/Readers');
