<?php

define('FRAMEWORK_DATABASE_ROOT', __DIR__ . '/..');
define('FRAMEWORK_DATABASE_BASECLASSES', FRAMEWORK_DATABASE_ROOT . '/Baseclasses');
define('FRAMEWORK_DATABASE_DATA', FRAMEWORK_DATABASE_ROOT . '/Data');
define('FRAMEWORK_DATABASE_FACTORIES', FRAMEWORK_DATABASE_ROOT . '/Factories');
define('FRAMEWORK_DATABASE_INTERFACES', FRAMEWORK_DATABASE_ROOT . '/Interfaces');
define('FRAMEWORK_DATABASE_VALIDATORS', FRAMEWORK_DATABASE_ROOT . '/Validators');
define('FRAMEWORK_DATABASE_WRAPPERS', FRAMEWORK_DATABASE_ROOT . '/Wrappers');