<?php

define('FRAMEWORK_GOOGLE_ROOT', __DIR__ . '/..');

define('FRAMEWORK_GOOGLE_BASECLASSES', FRAMEWORK_GOOGLE_ROOT . '/Baseclasses');
define('FRAMEWORK_GOOGLE_CREDENTIALS', FRAMEWORK_GOOGLE_ROOT . '/Credentials');
define('FRAMEWORK_GOOGLE_FACTORIES', FRAMEWORK_GOOGLE_ROOT . '/Factories');
define('FRAMEWORK_GOOGLE_INTERFACES', FRAMEWORK_GOOGLE_ROOT . '/Interfaces');
define('FRAMEWORK_GOOGLE_VALIDATORS', FRAMEWORK_GOOGLE_ROOT . '/Validators');
define('FRAMEWORK_GOOGLE_WRAPPERS', FRAMEWORK_GOOGLE_ROOT . '/Wrappers');