<?php

define('FRAMEWORK_RGDND_CREATURE_ROOT', FRAMEWORK_RGDND_ROOT . '/Libraries/Creature');
define('FRAMEWORK_RGDND_CREATURE_BASECLASSES', FRAMEWORK_RGDND_CREATURE_ROOT . '/Baseclasses');
define('FRAMEWORK_RGDND_CREATURE_CONFIG', FRAMEWORK_RGDND_CREATURE_ROOT . '/Config');
define('FRAMEWORK_RGDND_CREATURE_CONVERTERS', FRAMEWORK_RGDND_CREATURE_ROOT . '/Converters');
define('FRAMEWORK_RGDND_CREATURE_DATA', FRAMEWORK_RGDND_CREATURE_ROOT . '/Data');
define('FRAMEWORK_RGDND_CREATURE_FACTORIES', FRAMEWORK_RGDND_CREATURE_ROOT . '/Factories');
define('FRAMEWORK_RGDND_CREATURE_PERFORMERS', FRAMEWORK_RGDND_CREATURE_ROOT . '/Performers');
define('FRAMEWORK_RGDND_CREATURE_PRINTERS', FRAMEWORK_RGDND_CREATURE_ROOT . '/Printers');
define('FRAMEWORK_RGDND_CREATURE_READERS', FRAMEWORK_RGDND_CREATURE_ROOT . '/Readers');
define('FRAMEWORK_RGDND_CREATURE_UTILS', FRAMEWORK_RGDND_CREATURE_ROOT . '/Utils');

require_once(FRAMEWORK_RGDND_ROOT . '/Libraries/Shared/Config/config.php');